name: movie_app
description: 'Flutter movie app.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  go_router: ^12.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  internet_connection_checker_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: '#0E1324'
  image: assets/images/logo.png

flutter_icons:
  image_path: 'assets/icons/logo.png'
  image_path_android: 'assets/icons/logo.png'
  image_path_ios: 'assets/icons/logo.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/icons/logo.png'
    background_color: '#ffffff'
    theme_color: '#ffffff'
  windows:
    generate: true
    image_path: 'assets/icons/logo.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icons/logo.png'
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - environments/
    - assets/images/
    - assets/icons/
